### ISSUE TITLE
Setting up using non default namespace

### ISSUE THREAD

**Issue by aleksandrov** [nats-io/k8s#110]
I have kubectl configured to use my custom namespace instead default one. When I apply "curl -sSL https://nats-io.github.io/k8s/setup.sh | sh" to set things up it applying https://github.com/nats-io/k8s/blob/master/setup/bootstrap-policy.yml first and executes the rest of the steps.

Problem is bootstrap-policy.yml uses "default" namespace for serviceaccounts so later steps are unable to find service account for resources created my custom namespace.

Removing "namespace" from bootstrap-policy.yml solves the problem but maybe it is on purpose? If no, I can submit tiny PR to remove it.

**Comment by caleblloyd** [comment]
Closing due to age of issue; if experiencing in current versions please open a new issue.
