### ISSUE TITLE
helm install stan but got an error:

### ISSUE THREAD

**Issue by abserari** [nats-io/k8s#112]
Parse error on line 5: 'Expected a map value terminator "," or a map terminator "}", but got 's' instead.'

**Comment by wallyqs** [comment]
@abserari possible to share the configmap from the deploy or with `--debug` flag when deploying with Helm?

**Comment by abserari** [comment]
I add https://nats-io.github.io/k8s/helm/charts/ on rancher and launch stan chart with nothing update. Then I got the error.
![image](https://user-images.githubusercontent.com/32089134/92294189-46148100-ef5c-11ea-93b3-d7c465729e9b.png)

**Comment by wallyqs** [comment]
By the way seems this was because the `ns` parameter is required but without defining the configmap becomes invalid.
