### ISSUE TITLE
0.7.0 Helm install failed: parse error

### ISSUE THREAD

**Issue by dennybritz** [nats-io/k8s#152]
```
Helm install failed: parse error at (nats/templates/serviceMonitor.yaml:36): unexpected EOF
```

Not sure, but I think there may be a syntax error here (`else` instead of `end`?): https://github.com/nats-io/k8s/pull/151/files#diff-5eaac6ce5eabc035f5adc29c071f0dc97912abe770eed07428658cf2b5bf7996

**Comment by saggzz** [comment]
same here:
` "stderr_lines": ["Error: parse error at (stan/templates/serviceMonitor.yaml:36): unexpected EOF"]`
