### ISSUE TITLE
nats chart 0.7.0 release serviceMonitor label and annotations error

### ISSUE THREAD

**Issue by eoneal89** [nats-io/k8s#157]
When installing the nats 0.7.0 release with helm3, the install fails with the error ` parse error at (nats/templates/serviceMonitor.yaml:36): unexpected EOF`. This happens even if the serviceMonitor is not enabled. It appears to be related to an unclosed `if` statement; [this line](https://github.com/nats-io/k8s/blob/cdcc1ce9ee6256635da14aaec061a254562e7285/helm/charts/nats/templates/serviceMonitor.yaml#L8) is likely supposed to be `{{- end}}`.

The service monitor also fails with the error ` YAML parse error on nats/templates/serviceMonitor.yaml: error unmarshaling JSON: while decoding JSON` if labels or annotations are provided for the serviceMonitor.

**Comment by eoneal89** [comment]
After taking a second look, it looks like the namespace `if/else` statement was fixed, but the annotations and labels still cause an error if they are present

**Comment by eoneal89** [comment]
Fixed by #158

**Comment by wallyqs** [comment]
Thanks for the PR, release with the fix available now here: https://github.com/nats-io/k8s/releases/tag/v0.7.2
