### ISSUE TITLE
[helm/nats-operator] Add Support for Service Account Tokens

### ISSUE THREAD

**Issue by jyaworski** [nats-io/k8s#160]
I'm attempting to follow the [service token guidelines for nats-operator](https://github.com/nats-io/nats-operator#authorization) when I noticed that the `secret` objects for the service account tokens don't appear to get created. Reviewing this chart I see [this](https://github.com/nats-io/k8s/blob/master/helm/charts/nats-operator/values.yaml#L131), indicating that the chart doesn't support this configuration right now, even though `enableServiceAccounts` is a valid configuration. Can support be added for this? What would be involved? I could possibly add this if pointed in the right direction.

**Comment by wallyqs** [comment]
Here is an example of using service accounts with the nats-operator installed: https://github.com/nats-io/nats-operator/blob/master/example/example-cluster-service-accounts.yaml

To be able to use the service account bound tokens you need to enable a few extra APIs from Kubernetes: https://github.com/nats-io/nats-operator#authorization

**Comment by jyaworski** [comment]
@wallyqs that's what I was following, but I'm trying to map that to the helm chart rather than use those manifests directly. Is that possible on the current helm chart for nats-operator?

**Comment by wallyqs** [comment]
I'd suggest using the nats-operator to just create the deployment for the nats-operator only and then use a standalone yaml file to create the CRD of the NATS cluster.  To keep the NATS Operator helm chart simpler I'm thinking we should probably remove that section: https://github.com/nats-io/k8s/blob/master/helm/charts/nats-operator/values.yaml#L102-L104

**Comment by jyaworski** [comment]
Per my comment in #166, support already exists if using a separate manifest as indicated.
