### ISSUE TITLE
helm: advertise option should disable advertisements

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#184]
The following should disable client advertisements:

```
nats:
  advertise: false 
```

similar as:

```
noAdvertise: false
```

https://github.com/nats-io/k8s/blob/ba75d671bd0cdf3123b1ea27a2917e02939e9cc7/helm/charts/nats/templates/configmap.yaml#L146

**Comment by caleblloyd** [comment]
Closing due to age of issue; if experiencing in current versions please open a new issue.
