### ISSUE TITLE
helm chart for nats: Allow StatefulSet to relax its ordering guarantees

### ISSUE THREAD

**Issue by m1stegmann** [nats-io/k8s#189]
For cluster updates it would be better if" podManagementPolicy: Parallel" was set.
As far as I can see, nats does not require a fixed order in which pods are created.
In case of a cluster update the individual pods are started much faster on other nodes.

"In Kubernetes 1.7 and later, StatefulSet allows you to relax its ordering guarantees while preserving its uniqueness and identity guarantees via its .spec.podManagementPolicy field"

**Comment by caleblloyd** [comment]
It is Parallel by default now
