### ISSUE TITLE
nats-server-config-reloader is a 2 years old image

### ISSUE THREAD

**Issue by kamilgregorczyk** [nats-io/k8s#195]
Hello, the config reloader uses 2 years old image which should be rebuild, it's dangerous to use such old image, in addition to that, it only supports amd64 and nats & nats streaming has arm64 support

**Comment by kamilgregorczyk** [comment]
the same thing applies to `prometheus-nats-exporter`

**Comment by kamilgregorczyk** [comment]
`nats-boot-config`

**Comment by jonasmatthias** [comment]
Are there any updates on this matter?

I guess 
https://github.com/nats-io/k8s/blob/fcc254f5c682db2262a7c02b0f85915885225ea4/nats-server/nats-server-plain.yml#L179
should be replaced by the latest Docker image from
https://github.com/nats-io/prometheus-nats-exporter/releases

**Comment by xin3liang** [comment]
Any update on this matter+1. 
I am now deploying NATS on arm64(aarch64) platform also found that there is no nats-server-config-reloader image for arm64 arch. Anywhere to find arm64 images or way to build them.

**Comment by xin3liang** [comment]
Oh, I find arm64 images from here: https://hub.docker.com/u/natsio. Are these official built images? Anyway will have a try.

**Comment by wallyqs** [comment]
Yes we build and push those images

**Comment by wallyqs** [comment]
Closing since more recent images can be found here: https://hub.docker.com/u/natsio

**Comment by jonasmatthias** [comment]
This issue (in the k8s repo) should not be closed. The manifests in https://github.com/nats-io/k8s/tree/main/nats-server need to be updated to point to the recent images.

**Comment by xin3liang** [comment]
> This issue (in the k8s repo) should not be closed. The manifests in https://github.com/nats-io/k8s/tree/main/nats-server need to be updated to point to the recent images.

👍 I would like to post a PR to update them soon.

**Comment by xin3liang** [comment]
> > This issue (in the k8s repo) should not be closed. The manifests in https://github.com/nats-io/k8s/tree/main/nats-server need to be updated to point to the recent images.
> 
> 👍 I would like to post a PR to update them soon.

Great! See your update, thanks @jonasmatthias 💯 👍
