### ISSUE TITLE
nats/nats Helm chart not deployable on ARMv8/64

### ISSUE THREAD

**Issue by michalke-it** [nats-io/k8s#197]
Hello,
I noticed that it is currently not possible to deploy NATS on ARMv8 architecture by using a helm chart with default settings. Since I was able to compile the code and deploy the images successfully, it seems like there is just a simple issue with the Docker images. Namely, amd64 images are pulled for these images when deployed on ARMv8 devices:
* synadia/nats-box:0.4.0
* connecteverything/nats-server-config-reloader:0.6.0
* synadia/prometheus-nats-exporter:0.5.0
* connecteverything/nats-boot-config:0.5.2

In case you want to reproduce; I'm deploying on a K3s cluster with four Raspberry Pi 4's, K3s master is a virtual machine based on amd64.

Would be great if you could update the images, thank you!

PS; if someone encounters the same problem, simply edit the values.yaml and change each of the four image names to `michalkeit/imagename:tag`.

**Comment by wallyqs** [comment]
Thank you @michalke-it we are in the process of consolidating most images to be at https://hub.docker.com/u/natsio/ so we will make sure that we have those ARM images as well there. Thanks!

**Comment by michalke-it** [comment]
Thanks for the info @wallyqs !
@variadico would you ping here when this is stable? I would then simply try again and update you with the result.

**Comment by variadico** [comment]
As Wally mentioned, we're migrating images now, but here are the new locations for the images mentioned above. I added `linux/arm64` architecture to these images.

- [natsio/nats-box](https://hub.docker.com/r/natsio/nats-box/tags?page=1&ordering=last_updated):0.5.0
- [natsio/nats-server-config-reloader](https://hub.docker.com/r/natsio/nats-server-config-reloader/tags?page=1&ordering=last_updated):0.6.1
- [natsio/prometheus-nats-exporter](https://hub.docker.com/r/natsio/prometheus-nats-exporter/tags?page=1&ordering=last_updated):0.7.0
- [natsio/nats-boot-config](https://hub.docker.com/r/natsio/nats-boot-config/tags?page=1&ordering=last_updated):0.5.3

**Comment by michalke-it** [comment]
Hi everyone, sorry for the heavy delay. I just now came back to running this on Raspberry Pis again and as you said, the images are migrated to a different repo. However, there are again no workin  ARMv8 images pushed for two of the image tags:
- natsio/nats-server-config-reloader:0.6.1 (marked as ARMv8 but has actually a different architecture, see this:)
`docker run -ti natsio/nats-server-config-reloader:0.6.1
standard_init_linux.go:228: exec user process caused: exec format error
`
- natsio/nats-box:0.6.0

Maybe there is a problem with/gap in your CI pipeline?
Would appreciate a fix because we love your project, thanks!

**Comment by variadico** [comment]
We're currently working on improving our ARM release workflow. Here is a work-in-progress update.

These images have been updated to work on ARM. We tested on ARM 64 Ubuntu.

* [natsio/jetstream-controller:0.3.1](https://hub.docker.com/r/natsio/jetstream-controller/tags?page=1&ordering=last_updated)
* [natsio/nats-boot-config:0.5.4](https://hub.docker.com/r/natsio/nats-boot-config/tags?page=1&ordering=last_updated)
* [natsio/nats-server-config-reloader:0.6.2](https://hub.docker.com/r/natsio/nats-server-config-reloader/tags?page=1&ordering=last_updated)

**Comment by wallyqs** [comment]
ARM based images are now supported so closing, thanks for opening the issue.
