### ISSUE TITLE
Stan helm chart config with db credentials in plaintext ConfigMap

### ISSUE THREAD

**Issue by hpdobrica** [nats-io/k8s#200]
Hello! Im using [stan helm chart](https://github.com/nats-io/k8s/tree/master/helm/charts/stan) but I've come across a security issue which blocks me from using this. 

When using database store, the configmap used by the helm chart stores db credentials in plaintext [here](https://github.com/nats-io/k8s/blob/master/helm/charts/stan/templates/configmap.yaml#L72).

Also, the init-db script is also using db password directly [here](https://github.com/nats-io/k8s/blob/master/helm/charts/stan/templates/initdb.yaml#L26).

Would it be possible to turn the ConfigMap into a Secret so that the credentials are not visible on the cluster?

I'd be happy to create a PR if im not missing something?
Thanks!

**Comment by caleblloyd** [comment]
Closing due to age of issue; if experiencing in current versions please open a new issue.
