### ISSUE TITLE
[helm/nats] fails to report "not ready" when fail to connect to other nats nodes (routes)

### ISSUE THREAD

**Issue by kuznero** [nats-io/k8s#214]
It was observed that when a node fails to establish a connection to other nodes (specifically it was a certificate issue) it still appears as *Ready* in Kubernetes. This leads traffic its way, which is not desirable.

In general NATS should be able to read certificates from disk every time it fails to establish connection. Since Kubernetes can replace these certificates with new ones, it should be possible to establish connection with updated certificates.

**Comment by caleblloyd** [comment]
Healthz readiness checks are available now
