### ISSUE TITLE
[helm/nats-operator] podLabels: is not working in nats-operator helm chart

### ISSUE THREAD

**Issue by indra0007** [nats-io/k8s#216]
Whenever I am trying to put extra labels by using below config it's not working.
```
podLabels:
 key1: val1
 key2: val2
```
I think you have to use below configuration in line `https://github.com/nats-io/k8s/blob/master/helm/charts/nats-operator/templates/deployment.yaml#L32` to fix it. Please also do make changes for other places wherever it's been used

```
 {{- with .Values.podLabels }}
 {{- toYaml . | nindent 8 }}
 {{- end }}
```

**Comment by wallyqs** [comment]
@icelynjennings I believe so, will close the issue then. thanks
