### ISSUE TITLE
Allow annotations in nats configmap.yaml

### ISSUE THREAD

**Issue by huineng** [nats-io/k8s#224]
just like in statefull sets allow injection of annotations in configmap.yaml and add new field
configmapAnnotations in values.yaml

```
metadata:
  labels:
    {{- if .Values.configmapAnnotations}}
    annotations:
    {{- range $key, $value := .Values.configmapAnnotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
```

possible ?

thanks

**Comment by caleblloyd** [comment]
Supported in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats)
