### ISSUE TITLE
Helm index file not upadated

### ISSUE THREAD

**Issue by imesic-kolibree** [nats-io/k8s#225]
I'm trying to use the Helm chart by following the instructions from here https://github.com/nats-io/k8s/blob/master/helm/charts/nats/README.md, but also using Terraform. There, I'd like to pin the version and according to Chart.yaml from master, that is now 0.8.3. But, the index file at https://github.com/nats-io/k8s/blob/master/helm/charts/index.yaml has not been updated for a few months so I can't install it. 

Is there a reason for that and how can it be used?

**Comment by muka** [comment]
I am facing this issue too. As a temporary solution one can install the chart from a [local directory](https://helm.sh/docs/helm/helm_install/). In that way the chart reach the current version (`0.8.3` as of writing)

**Comment by muka** [comment]
I created the PR above that merges `master` with `gh-pages`, not sure if it break something. Happy to follow up if you provide a review.

**Comment by imesic-kolibree** [comment]
@muka Thanks for the PR. To me it looks good, let's hope someone from the maintainers can take a look.

**Comment by whyman** [comment]
It would be great if a maintainer could take a look at this one. Its pretty bad not being able to _use_ the latest/greatest version.

ping @wallyqs
