### ISSUE TITLE
nats > v2.2.1 result in "nats-server": executable file not found in $PATH:

### ISSUE THREAD

**Issue by muka** [nats-io/k8s#242]
Using anything but `nats:2.2.1-alpine3.13` fails consitently with this error (eg. `nats:2.2.2-scratch` or `nats:2.2` or ...). Chart is latest avail 0.8.x.

```
Error: failed to start container "nats": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "nats-server": executable file not found in $PATH: unknown
```

**Comment by wallyqs** [comment]
Thanks, we made the alpine the new default since it was complex to add new TLS certs to the scratch image, but would be great to add support to the scratch image again.

**Comment by muka** [comment]
Ok clear, if it is not already it could be mentioned in the docs. Thank you

**Comment by dash042** [comment]
I get that error with nats:2.7.2 using the helm script... 
what is the fix?

**Comment by wallyqs** [comment]
@dash042 you would have to specify `nats:2.7.2-alpine` instead at the moment
