### ISSUE TITLE
Pull operator and systemAccount from k8s configmap when resolver.type is `full`

### ISSUE THREAD

**Issue by sindreij** [nats-io/k8s#246]
Is it possible to fetch `operator` and `systemAccount` from a k8s configmap when resolver.type is full? I can't see any way of doing that. I'm thinking that it might be possible to for instance set systemAccount to a variable like `$SYSTEM_ACCOUNT`, however I cannot see how I can add a generic environment variable. Maybe it would be possible to add a `envFrom` in the stateful map if configured?

**Comment by caleblloyd** [comment]
Supported in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats)
