### ISSUE TITLE
Update information/guidelines

### ISSUE THREAD

**Issue by flowerinthenight** [nats-io/k8s#26]
Is there any guidelines on how to update an installation (via the one-liner) deployed inside k8s?

**Comment by wallyqs** [comment]
Currently the one liner only installs a version, but you could try to update the nats image for example with the `edit` command:

```
kubectl edit sts nats
```

Or updating the configuration map to change the settings (there is config reload support so this would be applied on the fly):

```
kubectl edit cm nats-config
```

**Comment by wallyqs** [comment]
We are also about to release a few Helm 3 charts that may help with this if you are more familiar with that flow.

**Comment by flowerinthenight** [comment]
Thank you. Yes, we are using helm so we will just wait for those chart releases.

**Comment by flowerinthenight** [comment]
Is this the chart you're referring to? Or updates to this chart?
https://github.com/helm/charts/tree/master/stable/nats

**Comment by wallyqs** [comment]
We will have an alternative version since those stable charts are getting moved/deprecated eventually, we are working on this branch: https://github.com/nats-io/k8s/pull/25

wip are here: https://github.com/nats-io/k8s/tree/master/helm/charts

Eventually the plan is to be able to install them like this:

```
helm repo add nats https://nats-io.github.io/k8s/helm/charts/
helm repo update

helm install my-nats nats/nats
helm install my-stan nats/stan --set stan.nats.url=nats://my-nats:4222
```

**Comment by flowerinthenight** [comment]
Brilliant. Thanks.

**Comment by wallyqs** [comment]
@flowerinthenight we have some available Helm 3 charts now that you can fetch as follows:

```sh
> helm repo add nats https://nats-io.github.io/k8s/helm/charts/
> helm repo update

> helm repo list
NAME          	URL 
nats          	https://nats-io.github.io/k8s/helm/charts/

> helm install my-nats nats/nats
> helm install my-stan nats/stan --set stan.nats.url=nats://my-nats:4222 --set stan.store.type=memory
```

**Comment by flowerinthenight** [comment]
Thanks. We'll move to this one since we use helm. The one-liner is good, and works, but quite difficult to manage.
