### ISSUE TITLE
Add support for optional serviceAccount creation

### ISSUE THREAD

**Issue by matyashlavacek** [nats-io/k8s#284]
We would like to add support for optional service account creation.

We are using PSP's and the current version of the chart doesn't allow us to use a service account unless we have external access and advertisement enabled. We currently don't want to have external access enabled. Which means that we won't have service accounts to associate the PSP roles.

https://github.com/nats-io/k8s/blob/1ca1450890fe6622d156a1f0d2cf2c1ff5589a09/helm/charts/nats/templates/rbac.yaml

**Comment by adonispd** [comment]
I've opened a PR to fix the creation of serviceAccount

**Comment by adonispd** [comment]
I've opened a PR to fix the creation of serviceAccount
