### ISSUE TITLE
startup probe to respect status of streams

### ISSUE THREAD

**Issue by m1stegmann** [nats-io/k8s#369]
During a node update or a rolling update, individual nats instances and thus also replicas of a js stream are temporarily offline. When such an instance comes back online, it may not be "in sync" with the other replicas if many new messages have arrived. 

It would be desirable if the startup probe would respect this circumstance and only report an OK when all js streams are "in sync" again.

**Comment by caleblloyd** [comment]
Healthz Startup probe is the default now and should address this
