### ISSUE TITLE
Add `namespaceOverride` to values.yaml

### ISSUE THREAD

**Issue by manuelottlik** [nats-io/k8s#397]
Hey guys,

I am currently using the `nats` and `nack` helm charts as helm subcharts in my project and would like to deploy its content to another namespace as my parent helm chart.

Therefore I would like to add the `namespaceOverride` property in addition to the `nameOverride` property and give everyone a chance to choose their desired namespace.

If this feature is welcome I can submit a PR implementing this feature in the same way as `nameOverride` was implemented.

Cheers!

**Comment by wallyqs** [comment]
Sounds good to me as an opt-in, feel free to send the PR!
