### ISSUE TITLE
Provide CRDs in `nack` helm chart

### ISSUE THREAD

**Issue by manuelottlik** [nats-io/k8s#398]
Hey guys,

when installing the `nack` helm chart I figured that the [CRDs for the JetStream controller](https://github.com/nats-io/nack/blob/main/deploy/crds.yml) are not installed. This is possible in an helm chart by providing a `crds` folder next to `templates` ([see helm docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource)).

I think the `nack` helm chart should provide these CRDs. Do you agree? I would be happy to provide a PR for this.

**Comment by wallyqs** [comment]
Thanks @manuelottlik, they used to be part of the Helm chart but we took them out because that meant that updates to the CRDs were not being applied and these CRDs can have new fields fairly often.  Managing CRDs via Helm has many gotchas as described in the following discussion from Helm maintainers, so for now decided to keep them out of the repo: https://github.com/helm/community/blob/main/hips/hip-0011.md#helm-is-still-working-on-thus-but-we-cannot-solve-it-alone

**Comment by manuelottlik** [comment]
Thank you for the quick reply, @wallyqs. There are two things I would like to say:

1. Couldn't we just provide the CRDs in the `crds` folder and give a migration guide whenever there is a new version with changed definitions? The migration guide could contain a `kubectl apply -f ...` link that users of the helm chart could copy to update their CRDs in their cluster. Since users of the helm chart have to do this anyways in order to update this helm chart, it feels like the best UX for me.
2. If CRDs will not be included, this should be stated somewhere in the documentation / README of this helm chart. A link to the CRD file etc. would be nice. New versions that require updated CRDs should also have some kind of migration guide. I would open a PR if you want me to.

What do you think?

**Comment by wallyqs** [comment]
I think both sounds good, just noticed that they are not mentioned in the readme, agree that we need a migration guide / better strategy for handling updates to the CRDs as well...  For a bit there used to be a copy of the CRDs both in these repo and in the nack repo but eventually only left this copy since there was some confusion with duplication: https://github.com/nats-io/nack/blob/main/deploy/crds.yml

**Comment by manuelottlik** [comment]
Hey @wallyqs, of course:
* https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
* https://github.com/traefik/traefik-helm-chart/tree/master/traefik
* https://github.com/grafana/helm-charts/tree/main/charts/agent-operator
* https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator
* https://github.com/bitnami/charts/tree/master/bitnami/grafana-operator
* [and many bitnami charts more](https://github.com/bitnami/charts/search?q=apiextensions)

**Comment by wallyqs** [comment]
Thanks, I think our approach might be similar to how grafana does with the agent-operator in that they are synced from another repo:
https://github.com/grafana/helm-charts/tree/main/charts/agent-operator#crds
https://github.com/grafana/agent/tree/main/production/operator/crds

**Comment by manuelottlik** [comment]
Okay @wallyqs, so you plan on keeping it that way? If thats the case, this issue can be closed.

**Comment by wallyqs** [comment]
Hi @manuelottlik I meant that we could do a similar approach like grafana does and keep a copy of the crds in both places probably.

**Comment by manuelottlik** [comment]
Hey @wallyqs, I see. Should I just provide a PR with the copied helm charts from the other repository? Should there be any note in the README about the need to keep these up to sync or will you handle that internally?

**Comment by mathieubergeron** [comment]
Hi @manuelottlik, @wallyqs,

I wonder why this issue was closed? CRDs are still provided separately, which complicates automatically updating our dependency on nack.

Thanks!

**Comment by manuelottlik** [comment]
Hey @mathieubergeron, that's right. I closed it as "not planned" because I did not receive any more feedback. I still think it's a good idea but stopped using the CRDs, so I didn't put in more effort.

**Comment by wallyqs** [comment]
Sorry @manuelottlik should have responded that your approach sounded good. I think it might be fine to put them now in the Helm charts as well with the caveat that in case there are updates to the CRDs they won't be updated and still has to be done manually.

**Comment by christiang830** [comment]
As a gitops user it would be really really good to have the CRDs included in the chart. Is there an update when this open PR is going to be merged? Thank you

**Comment by manuelottlik** [comment]
Hey @christiang830, I stopped working on this since we do not use the CRDs at the moment, you are welcome to create a PR.

**Comment by christiang830** [comment]
Hi @manuelottlik, thanks for the quick reply. But there is already an open PR [#694](https://github.com/nats-io/k8s/pull/694)

**Comment by manuelottlik** [comment]
Ah oops, did not see that. I am not a maintainer, so I do not have control about merging it.

**Comment by christiang830** [comment]
Ah sorry, assumed from the previous replies that you actually were. My bad
