### ISSUE TITLE
After nats-box v0.6.0, only amd64 images published to Docker Hub

### ISSUE THREAD

**Issue by tbeets** [nats-io/k8s#413]
I am deploying the `nats/nats` helm chart to arm64 hosts.  The `natsio/nats-box:latest` image points to older `0.6.0` tag which does have arm builds, but the later versions of nats-box are amd64 only.

Possible to get updated builds with latest NATS CLI, etc. for both amd64 and arm64?

**Comment by wallyqs** [comment]
Thanks for the report, it should be fixed now.
