### ISSUE TITLE
INSTALLATION FAILED

### ISSUE THREAD

**Issue by alifpay** [nats-io/k8s#416]
Error: INSTALLATION FAILED: template: nats/templates/statefulset.yaml:484:28: executing "nats/templates/statefulset.yaml" at <semver $tag>: error calling semver: Invalid Semantic Version

helm version 3.7.2

**Comment by wallyqs** [comment]
could you share the image tag version example to try to reproduce?

**Comment by alifpay** [comment]
problems was values.yaml, I try install with old values.yaml

changed with new values it is installed..

thank you
