### ISSUE TITLE
Add option to just mount cluster certs without enabling TLS

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#434]
Sometimes a user would decide to go from having live traffic for the cluster routes without TLS setup to having TLS setup, but doing that requires a rollout of the cluster to mount the certificates. One workaround with less downtime could be to be able to do a rollout without TLS enabled yet, but with the certs mounted, and then do another helm upgrade that just updates the cluster configuration to enable TLS.

**Comment by caleblloyd** [comment]
Can be done via merging/patching in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats)
