### ISSUE TITLE
[nats helm] Support Non-Homogenous Clusters

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/k8s#440]
A user may want to create multiple types of Servers within a cluster, example

- 3x StatefulSet `nats`, JetStream `disabled`
- 3x StatefulSet `nats-js`, JetStream `enabled`

Also consider the case where a StatefulSet setting that does not support updates, such as `volumeClaimTemplates`, must be changed.  The user could perform a multi-phase update:

Deployment 1:
- 3x StatefulSet `nats-js`, JetStream `enabled`, persistence: `disabled`

Deployment 2:
- 2x StatefulSet `nats-js`, JetStream `enabled`, persistence: `disabled`
- 1x StatefulSet `nats-js-pvc`, JetStream `enabled`, persistence: `enabled`

Deployment 3:
- 1x StatefulSet `nats-js`, JetStream `enabled`, persistence: `disabled`
- 2x StatefulSet `nats-js-pvc`, JetStream `enabled`, persistence: `enabled`

Deployment 4:
- 3x StatefulSet `nats-js-pvc`, JetStream `enabled`, persistence: `enabled`

**Comment by vukasin-nikodijevic** [comment]
I found this strange too - chart should support this a it seems to be originally in the NATS architecture design.

**Comment by svallebro** [comment]
We recently ran into an issue related to this. Where we needed to extend the PVC size. This would have been really handy.

**Comment by caleblloyd** [comment]
[nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats) should have enough knobs to turn where combining 2 Helm deployments into 1 cluster is not as difficult
