### ISSUE TITLE
[nats helm] Config Reloader sidecar vs Helm Managed Config

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/k8s#443]
**Pros of Config Reloader sidecar:**

- Allows for external processes to modify ConfigMaps / Config Files and have configuration reloaded

*Cons of Config Reloader sidecar:*

- All pods pick up new configuration and send reload signal at the same time - potential disruption?
- Unchecked rollout of a bad configuration:

*Current Case 1*
Config: Bad but Valid
Config Reloader: Enabled
1. Helm deployment starts
2. New ConfigMap is deployed, replacing the old ConfigMap
3. The Helm deployment will succeed
4. The Config Reloader container will reload the configuration
5. Healthchecks could begin to fail, and all Pods could be marked as Not Ready

*Current Case 2*
Config: Invalid
Config Reloader: Enabled
1. Helm deployment starts
2. New ConfigMap is deployed, replacing the old ConfigMap
3. The Helm deployment will succeed
4. The Config Reloader container will attempt to reload the configuration, but NATS will reject it as invalid
5. Some time later the pod could get rescheduled, and would fail to start back up due to the invalid config

**Alternative: Helm Managed Config**

Use an annotation to automatically roll out configuration changes:
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

This will cause StatefulSets to restart pods 1-at-a-time.  If there is a configuration-related startup issue, Helm will fail if it is run with the `--wait` flag and can optionally roll back with the `--atomic` flag

**Comment by wallyqs** [comment]
This sounds good, the Helm Managed Config approach would also help out with some of reloading features that are a bit behind right now like leafnodes `remotes` reloading. One of the workarounds from users has been to change the reload signal from HUP to USR2 for example so that the reloader restarts the pod instead, but then there is not a lot of control on the rollout and could cause multiple restarts at the same time, so this sounds like a safer way to manage the config updates.

**Comment by caleblloyd** [comment]
Are there other configuration files that the Config Reloader is still useful for?  Such as resolvers?

Trying to figure out if we should default the Config Reloader to Off or just to a limited set of configuration files.

**Comment by wallyqs** [comment]
Not all the resolver config fields are reloadable aware. There were some pending issues like tracking changes to TLS certs and signal update when the certs change (https://github.com/nats-io/k8s/issues/101) so could be useful for that, but to make the deployment simpler and predictable by default I think sounds good to disable it and let Helm manage the rollout on changes instead.

**Comment by caleblloyd** [comment]
It probably makes sense to use both the `checksum` and `reloader`

`reloader` will only work for configurations that _can_ be reloaded, and will fail with a message when a configuration is not re-loadable, such as an Operator JWT.  Still, it is useful for things like bumping debug/trace log levels without restarting the server if needed

`checksum` will only take effect on Helm upgrades, but will force a StatefulSet rollout for any configuration change, ensuring that any type of configuration change is applied

**Comment by caleblloyd** [comment]
It probably makes sense to use both the `checksum` and `reloader`

`reloader` will only work for configurations that _can_ be reloaded, and will fail with a message when a configuration is not re-loadable, such as an Operator JWT.  Still, it is useful for things like bumping debug/trace log levels without restarting the server if needed

`checksum` will only take effect on Helm upgrades, but will force a StatefulSet rollout for any configuration change, ensuring that any type of configuration change is applied
