### ISSUE TITLE
[nats helm] Enable Persistence by default if Jetstream is enabled

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/k8s#458]
Cluster Meta RAFT Groups use disk persistence.  For the best possible user experience, we should enable disk persistence by default.

This will be a breaking change for anyone who already has JetStream enabled without persistence, since `volumeClaimTemplates` on StateflSets are immutable.  The blue-green upgrade method described in #440 will become important

**Comment by wallyqs** [comment]
Maybe we should make the specific volume size for file storage a required parameter in case none specified?
