### ISSUE TITLE
Allow to specify the `websocket.handshake_timeout` for NATS chart

### ISSUE THREAD

**Issue by manifest** [nats-io/k8s#462]
Allow to specify the [websocket.handshake_timeout](https://docs.nats.io/running-a-nats-service/configuration/websocket/websocket_conf) for the [NATS chart](https://artifacthub.io/packages/helm/nats/nats) .

We're currently experiencing an authorization error with NATS WS clients and the default 2-second timeout on the server side.

```
NatsError: "Authentication Timeout"
```

**Comment by manifest** [comment]
Any update on this issue?

_At the moment we need to update `nats.conf` in the kubernetes cluster manually after every deploy of NATS._

**Comment by caleblloyd** [comment]
Just opened a PR for it

**Comment by wallyqs** [comment]
@manifest I believe it should be available already

**Comment by manifest** [comment]
On the [artifacthub](https://artifacthub.io/packages/helm/nats/nats), I see only 1.15.1 without the [fix](https://artifacthub.io/packages/helm/nats/nats?modal=template&template=configmap.yaml).

**Comment by manifest** [comment]
I was thinking about artifacthub.io as a source of truth. Should I look to another Helm chart repo?

**Comment by caleblloyd** [comment]
We will be publishing a chart within the next week or so when a new NATS server version gets cut
