### ISSUE TITLE
`nats.jetstream.enabled = true` doesn't seem to enable `JetStream`

### ISSUE THREAD

**Issue by hypdeb** [nats-io/k8s#484]
Hello,

I am deploying `NATS` as a dependency of my Helm chart like this

``` Chart.yaml
dependencies:
  - name: nats
    version: "0.15.1"
    repository: "file://../../nats-k8s/helm/charts/nats"
```
Furthermore, I am enabling `JetStream` (or so I thought) by adding the following to my values
``` values.yaml
nats:
  jetstream:
    enabled: true
```
But when I run `nats account info --server=nats` I get the following
```
Connection Information:

               Client ID: 52
               Client IP: 192.168.110.33
                     RTT: 436.913µs
       Headers Supported: true
         Maximum Payload: 1.0 MiB
           Connected URL: nats://nats:4222
       Connected Address: 192.168.110.35:4222
     Connected Server ID: NBAD7QKYKNLLBUI5EOK2ZTNLO3RQJKUSH6X64ZCIZFQC27KPTA7UJNA4
   Connected Server Name: nats-0

JetStream Account Information:

   JetStream is not supported in this account
```
Are there other steps one has to take to enable JetStream that I am not aware of or is this a bug ?

**Comment by wallyqs** [comment]
within your account you also have to specify `jetstream: enabled`

**Comment by hypdeb** [comment]
Thanks for the quick reply.

Is there a way of setting that through Helm values for the default account ? I have not created any account, therefore I assume there's a default one that I'm using by not specifying any account.

**Comment by hypdeb** [comment]
Hmmm, I also have
```
auth:
  enabled: false
```

Shouldn't that disable the whole account feature altogether ?

**Comment by hypdeb** [comment]
I found the issue, it's my bad. Turns out I didn't see that `jetstream` was nested inside the `nats` section of your chart, meaning my values should look like this
```
nats:
  nats:
    jetstream:
      enabled: true
```
Best use of a whole evening...

**Comment by wallyqs** [comment]
Sorry about that @hypdeb, glad you found the issue..
