### ISSUE TITLE
Add ca_bundle flag for TLS block

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#486]
Make it possible to use a different CA for a certain TLS block rather than the one from a secret, similar to how nats-operator did it here: https://github.com/nats-io/nats-operator/commit/ecc863a5b

**Comment by caleblloyd** [comment]
Supported in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats) via merging or patching the TLS config
