### ISSUE TITLE
Config Reloader v0.6.3 Crash Loop on "Too Many Open Files"

### ISSUE THREAD

**Issue by Kampe** [nats-io/k8s#488]
Hello!

We're seeing strange issues with our config-reloader using the latest build from February (v0.6.3) - config reloader pods will not boot with logs stopping at:

```
2022/04/18 19:37:26 Starting NATS Server Reloader v0.6.3
Error: too many open files
```

Is anyone else seeing this?  I'm able to show this reproducing in multiple clusters (k3s) unfortunately, while sometimes the container launches just fine.

Have attempted to utilize older versions as well (0.6.1 and 0.6.2) with the same issue happening unfortunately.

**Comment by caleblloyd** [comment]
Sounds like a ulimit problem on the machine

**Comment by caleblloyd** [comment]
Closing due to age of issue; if experiencing in current versions please open a new issue.
