### ISSUE TITLE
NATS Helm JWT store custom StorageClassName

### ISSUE THREAD

**Issue by Gylleus** [nats-io/k8s#495]
Hi all!

I am trying to deploy a NATS JetStream cluster with the NATS JWT resolver by using the helm chart in this repo. While it is possible to set the StorageClassName for the [JetStream file storage](https://github.com/nats-io/k8s/blob/main/helm/charts/nats/templates/statefulset.yaml#L625-L627) it does not seem to be possible for the JWT store data which causes trouble in my case. 

If there is no reason why this is not supported I could write a simple fix to be able to set a custom storage class for it.

**Comment by caleblloyd** [comment]
Will gladly accept a PR for it! Thanks!
