### ISSUE TITLE
Confusion about container images (nats-operator)

### ISSUE THREAD

**Issue by sebastiangaiser** [nats-io/k8s#507]
Hi 👋🏻,

I want to try NATS on Kubernetes and had a look to the deployed images referenced in the [nats-operator](https://github.com/nats-io/k8s/tree/main/helm/charts/nats-operator) Helm chart.
The referenced image[ `connecteverything/nats-operator:0.7.4`](https://hub.docker.com/r/connecteverything/nats-operator) is more than 2 years old. Then I searched around the Docker Hub and found an other image: [`natsio/nats-operator:0.8.3`](https://hub.docker.com/r/natsio/nats-operator)

Was there a migration of the images in the past?
If that's the case, can you please finish the migration, also for the Helm charts.

**Comment by wallyqs** [comment]
Thanks @sebastiangaiser we should be pointing to the `natsio/nats-operator:0.8.3` container image, for new deployments we recommend using the Helm charts instead since they have more features and more flexible as well.
