### ISSUE TITLE
Using `/` instead of `/healthz` for health check

### ISSUE THREAD

**Issue by 1995parham** [nats-io/k8s#519]
Is there any specific reason for using `/` instead of `/healthz` for health check? We had some issues on consumers or stream clusters that go down, but we didn't notice because `/` is working correctly, and we had errors on `/healthz`.

https://github.com/nats-io/k8s/blob/19a57ecb21fb40b36f9a26c05304142bdd4eafb4/helm/charts/nats/templates/statefulset.yaml#L413

**Comment by caleblloyd** [comment]
A server could be perfectly healthy but `/healthz` still fail, in the case that other parts of the JetStream cluster are not healthy.  So for Readiness and Liveness the check is simply `/` because we don't want to kill a healthy pod...

**Comment by 1995parham** [comment]
@caleblloyd thank you for your response.
