### ISSUE TITLE
PodAntiAffinity on NACK deployment prevents rollouts on single node clusters

### ISSUE THREAD

**Issue by chris13524** [nats-io/k8s#522]
From Slack:

> I'm using the nack chart, but sometimes when I upgrade it I get this error on the Deployment: 0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. I am not providing any values for affinity . I believe the anti-affinity is failing because there is still a running replica of the deployment that matches the app name specified in the anti-affinity rules. If I delete this other replica, then the Deployment succeeds. My question is why this doesn't terminate by itself (edited) 

https://natsio.slack.com/archives/CTM4A2TR7/p1656711984697349?thread_ts=1656690643.999329&cid=CTM4A2TR7

**Comment by caleblloyd** [comment]
I am not sure why PodAntiAffinity is in that deployment we can probably remove it
