### ISSUE TITLE
Feature request: expose `automountServiceAccountToken` in PodSpec

### ISSUE THREAD

**Issue by odubajDT** [nats-io/k8s#527]
Hi,

Would there please be a possibility to expose `automountServiceAccountToken` (https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) as a configurable value? Is there a reason why only `serviceAccountName` is exposed in PodSpec?

Thank you.

**Comment by odubajDT** [comment]
Looks good, thank you very much :) Will it be part of nats-0.17.2?

Thank you in advance.

**Comment by caleblloyd** [comment]
yes, it is in nats-0.17.2 now!

**Comment by odubajDT** [comment]
Thank you very much for the quick implementation! :+1:

**Comment by odubajDT** [comment]
Hello, just applied version 0.17.2 and there seems to be a small issue with the if statement:

$ helm template keptn/ --debug
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/odubaj/KEPTN/keptn/installer/manifests/keptn


Error: template: keptn/charts/nats/templates/statefulset.yaml:200:17: executing "keptn/charts/nats/templates/statefulset.yaml" at <eq .Values.nats.automountServiceAccountToken false>: error calling eq: incompatible types for comparison
helm.go:81: [debug] template: keptn/charts/nats/templates/statefulset.yaml:200:17: executing "keptn/charts/nats/templates/statefulset.yaml" at <eq .Values.nats.automountServiceAccountToken false>: error calling eq: incompatible types for comparison

Seems like a default value of `null` should not be used in the values.yaml, but I am not an expert in charts.

Thank you!

**Comment by odubajDT** [comment]
created a separate issue https://github.com/nats-io/k8s/issues/530
