### ISSUE TITLE
nats helm release 0.17.2 installation fails when using default flags

### ISSUE THREAD

**Issue by nicolauscg** [nats-io/k8s#529]
running `helm install my-nats nats/nats` with version 0.17.2 leads to the following error

```
Error: INSTALLATION FAILED: template: nats/templates/statefulset.yaml:200:17: executing "nats/templates/statefulset.yaml" at <eq .Values.nats.automountServiceAccountToken false>: error calling eq: incompatible types for comparison
``` 

current workaround is to either use "--version 0.17.1" or add extra flags "--set nats.automountServiceAccountToken=true --set natsbox.automountServiceAccountToken=true"

should install work without specifying any additional flags?

**Comment by caleblloyd** [comment]
What version of `helm`?  I cannot recreate

**Comment by nicolauscg** [comment]
the helm version I used is `version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}`
