### ISSUE TITLE
Helm: support configuration of auth for STAN

### ISSUE THREAD

**Issue by kylos101** [nats-io/k8s#53]
Hi,

Is there a way to enable auth for STAN using Helm? For example, would it help if I updated [this](https://github.com/nats-io/k8s/blob/master/helm/charts/stan/templates/configmap.yaml) to include credential stuff like [this](https://github.com/nats-io/k8s/blob/master/nats-streaming-server/nats-streaming-auth.yml#L15)?

I installed NATS without auth using [this chart](https://hub.kubeapps.com/charts/bitnami/nats), because [this STAN chart](https://hub.kubeapps.com/charts/nats/stan) does not have configuration for auth.

Thanks a lot for your help!

**Comment by lmorais** [comment]
I think that from now its only possible to control that using service accounts as a described here: https://github.com/nats-io/nats-operator#using-serviceaccounts

**Comment by kylos101** [comment]
This works well for me, thank you @lmorais !
