### ISSUE TITLE
bug: `automountServiceAccountToken` defaults to null

### ISSUE THREAD

**Issue by odubajDT** [nats-io/k8s#530]
Hello, just applied version 0.17.2 and there seems to be a small issue with the if statement:

$ helm template . --debug
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/odubaj/KEPTN/keptn/installer/manifests/keptn

Error: template: keptn/charts/nats/templates/statefulset.yaml:200:17: executing "keptn/charts/nats/templates/statefulset.yaml" at <eq .Values.nats.automountServiceAccountToken false>: error calling eq: incompatible types for comparison
helm.go:81: [debug] template: keptn/charts/nats/templates/statefulset.yaml:200:17: executing "keptn/charts/nats/templates/statefulset.yaml" at <eq .Values.nats.automountServiceAccountToken false>: error calling eq: incompatible types for comparison

Seems like a default value of `null` should not be used in the `values.yaml` as `null` cannot be compared with boolean value, but I am not an expert in charts and it might be something else.

Thank you!

**Comment by caleblloyd** [comment]
What version of `helm`?  I cannot recreate with 3.9.2

**Comment by odubajDT** [comment]
helm version 3.4.1. I will try to upgrade and test

**Comment by caleblloyd** [comment]
OK now I see that issue with 3.4.1 but they must have fixed it in a later version of helm, updating should fix

**Comment by odubajDT** [comment]
With higher version works, sorry for the noise and thank you :)
