### ISSUE TITLE
[nats helm] allow_non_tls should be allowNonTLS

### ISSUE THREAD

**Issue by NickLarsenNZ** [nats-io/k8s#534]
Given this

https://github.com/nats-io/k8s/blob/7e658c542e133dcc7386903ef5aac9d320b1c93f/helm/charts/nats/templates/configmap.yaml#L56-L58

The value should be `allowNonTLS`

https://github.com/nats-io/k8s/blob/7e658c542e133dcc7386903ef5aac9d320b1c93f/helm/charts/nats/values.yaml#L257

or perhaps keep it the same as in the nats config, and update the ConfigMap template.

**Comment by wallyqs** [comment]
You are right, this is just the comment though so we can just update in the comment.

**Comment by NickLarsenNZ** [comment]
Oh, I can fix that comment in my already opened PR #535
