### ISSUE TITLE
[nats helm] verify_cert_and_check_known_urls option isn't configurable for Custer TLS

### ISSUE THREAD

**Issue by NickLarsenNZ** [nats-io/k8s#535]
To be able to use TLS client authentication, the following options need configuring:

```
cluster {
  verify: true
  verify_and_map: true
  verify_cert_and_check_known_urls: true
}
```

The first two options are overridable by Helm (`verify` and `verifyAndMap`), however `verify_cert_and_check_known_urls` is not.

It looks like a helper template is filtering a specific set of options:

https://github.com/nats-io/k8s/blob/7e658c542e133dcc7386903ef5aac9d320b1c93f/helm/charts/nats/templates/_helpers.tpl#L104-L134

**Comment by wallyqs** [comment]
you can use `verifyAndMap` instead of `verify_and_map` looks like but `verify_cert_and_check_known_urls` is indeed missing

**Comment by NickLarsenNZ** [comment]
Correct regarding `verifyAndMap` (I'd already mentioned that), but I didn't make it clear that my example wasn't a helm values example, it was the real NATS config which uses underscored.

**Comment by NickLarsenNZ** [comment]
@wallyqs I've created a PR, using the attribute name as you suggested.
