### ISSUE TITLE
nats-operator 0.8.3 release in charts 

### ISSUE THREAD

**Issue by primeroz** [nats-io/k8s#550]
I can see nats operator 0.8.3 was released https://github.com/nats-io/nats-operator/releases/tag/v0.8.3 a long time ago but no updated chart was ever released ( last one is 0.7.4 ) which is required on kubernetes 1.22 

is the operator chart still alive ?

**Comment by wallyqs** [comment]
not very active since the nats helm chart has more functionality like JetStream so that one is recommended instead for new deployments

**Comment by primeroz** [comment]
thanks
