### ISSUE TITLE
The metrics port 7777 is defined two times in the statefulset

### ISSUE THREAD

**Issue by pskiwi** [nats-io/k8s#556]
First occurence: 
[Container "exporter"](https://github.com/nats-io/k8s/blob/81418cf9f9c0228a767941fac09123dc197389e5/helm/charts/nats/templates/statefulset.yaml#L558)

Second: occurence, maybe wrong, because the *nats* container has no open port 7777
[Container "nats"](https://github.com/nats-io/k8s/blob/81418cf9f9c0228a767941fac09123dc197389e5/helm/charts/nats/templates/statefulset.yaml#L279)

this results in two time series generated from the [prometheus operator](https://github.com/prometheus-operator/prometheus-operator) when using a PodMonitor and and a podMetricsEndpoints of "metrics".

**intended solution:** remove `containerPort: 7777` from the *nats* container spec.

**Comment by caleblloyd** [comment]
Thank you for catching that, I opened a PR to fix
