### ISSUE TITLE
using NATS Resolver setup example can't activate system-account

### ISSUE THREAD

**Issue by Doslin** [nats-io/k8s#563]
~ # nats str ls --creds /etc/nats-config/creds/sys.creds 
nats: error: could not list streams: context deadline exceeded, try --help
~ # hostname
zhilin-nats-box-6db9c7c9d6-pwphb
~ # cat /etc/nats-config/creds/sys.creds 
-----BEGIN NATS USER JWT-----
eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJLT0QyWFhFQ0RDVkhSVFUyRjRLWDNUTVZMREJXSTdRSElHV083TzZRNVdSNFdPUlQySzdRIiwiaWF0IjoxNjYyMDk5MjI2LCJpc3MiOiJBQVJFTVlBU0tCSk9OM0VYUVZQN0ZZSklKNEhGSDRUVkk1Q05WS1JJN1ZENktMNExCUjZFUTdCRyIsIm5hbWUiOiJzeXMiLCJzdWIiOiJVQkhMN1BYRFI0VUdGS0k2Nk9HNDVGWloyNkZXS0k3Nk80WERZV05JSjdCM0ZFTk9KT0YzWVlIUyIsIm5hdHMiOnsicHViIjp7fSwic3ViIjp7fSwic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwidHlwZSI6InVzZXIiLCJ2ZXJzaW9uIjoyfX0.dV9yCPYgHYg9MUDiEjCirnSfutwrr0ZO3SJVrwRQDOT2-CzJXSbNYmnAFHMRdvjEoA_Jd9tqqNe59hpo7PgNDg
------END NATS USER JWT------

************************* IMPORTANT *************************
NKEY Seed printed below can be used to sign and prove identity.
NKEYs are sensitive and should be treated as secrets.

-----BEGIN USER NKEY SEED-----
SUAHSFLY4KM4GMWISO7T6J6L2JOCTDV4L4SDVOGXDSKHGA5TP2INGZXKE4
------END USER NKEY SEED------

*************************************************************~ #

**Comment by wallyqs** [comment]
system account cannot use JS Stream API so would get an error... think that is what happened here
