### ISSUE TITLE
JetStream Readiness / Liveness probes

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/k8s#576]
Currently we are checking HTTP GET of `/` on the monitoring port for Liveness / Readiness

We _could_ be checking `/healthz?js-server-only=true`:

https://github.com/nats-io/nats-server/blob/main/server/monitor.go#L3049-L3052

If JetStream is enabled, this would check that:

- JetStream has established connection with meta leader
- JetStream is current with meta leader

The main concern here is unintentionally causing a cascading failure.  Example would be a meta leader change followed by it taking a while to catch up.  `/healthz?js-server-only=true` will fail during this, but killing this pod will not "help", it just needs time to catch up

Is this a good idea to enable?  What would reasonable defaults for polling frequency and number of failures be?

/cc @tbeets @wallyqs @derekcollison

**Comment by danielcibrao-form3** [comment]
@caleblloyd and @wallyqs if you do not see any issue I think that I would much rather have this approach then simply calling a `/` which does not validate anything related with NATS internals.
