### ISSUE TITLE
nats helm chart bootconfig image typo

### ISSUE THREAD

**Issue by eminden** [nats-io/k8s#609]
https://github.com/nats-io/k8s/blob/e87b0017e2a50045cb55b00fc409b24e0bea8627/helm/charts/nats/templates/statefulset.yaml#L235

this line should be updated as below on chart version `0.19.0`

```
        image: {{ include "nats.image" .Values.bootconfig.image }}
```

**Comment by caleblloyd** [comment]
:+1: good catch
