### ISSUE TITLE
Nats box service account issue in Openshift environment

### ISSUE THREAD

**Issue by bhati-github** [nats-io/k8s#611]
Basic Info: 
nats helm chart version: 0.17.4
test environment: Openshift cluster

I am passing some parameters to nats helm chart as follows:

![image](https://user-images.githubusercontent.com/49303596/205576882-0b5cf7c5-afa0-4818-8a6c-225df93d7a25.png)

I wish that a new serviceAccount is not required to be created and just use the already prsent serviceAccount "smo-ric-common-infra-sa". But, In openshift environment, this new service account is not assigned to nats-box pod and "default" serviceaccount is assigned to nats-box. **So, this is an issue in nats-box.yaml file.**

I have to add these lines in templates/nats-box.yaml file, then it works fine.
![image](https://user-images.githubusercontent.com/49303596/205579622-fa6b08e4-5132-4543-8de6-d4d75eec5e0a.png)

I verified in the pod spec that my desired serviceAccount name is present.
![image](https://user-images.githubusercontent.com/49303596/205579868-b2c6b92c-a368-48db-9fe4-2e890ef3e3d0.png)

**Comment by caleblloyd** [comment]
Service Accounts can be created for `nats` and `nats-box` in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats)
