### ISSUE TITLE
Unable to setup NATS in k8s 

### ISSUE THREAD

**Issue by Vaibhavi-Tanla** [nats-io/k8s#624]
please find the config below

nats.conf:
```
----
# NATS Clients Port
port: 4222

# PID file shared with configuration reloader.
pid_file: "/var/run/nats/nats.pid"

###############
#             #
# Monitoring  #
#             #
###############
http: 8222
server_name:$POD_NAME
###################################
#                                 #
# NATS Full Mesh Clustering Setup #
#                                 #
###################################
cluster {
  port: 6222
  name: tanla-hub-cluster

  routes = [
    nats://nats-0.nats.default.svc:6222
    nats://nats-1.nats.default.svc:6222
    nats://nats-2.nats.default.svc:6222
  ]
  cluster_advertise: $CLUSTER_ADVERTISE

  connect_retries: 120
}
```

ERROR:
```
[7] 2022/12/27 12:49:32.478300 [INF] 192.168.100.4:35602 - rid:26 - Route connection created
[7] 2022/12/27 12:49:38.240394 [INF] 192.168.100.5:38180 - rid:25 - Router connection closed: Read Error
[7] 2022/12/27 12:49:38.486128 [INF] 192.168.100.4:35602 - rid:26 - Router connection closed: Read Error
[7] 2022/12/27 12:49:44.160927 [INF] 192.168.100.6:16535 - rid:28 - Route connection created
[7] 2022/12/27 12:49:44.493842 [INF] 192.168.100.4:5095 - rid:29 - Route connection created
[7] 2022/12/27 12:49:50.170951 [INF] 192.168.100.6:16535 - rid:28 - Router connection closed: Read Error
[7] 2022/12/27 12:49:50.498316 [INF] 192.168.100.4:5095 - rid:29 - Router connection closed: Read Error
```

Why are we getting this errors?

are we missing anything please suggest

**Comment by caleblloyd** [comment]
Each of the pods needs to be able to connect to Port 6222 in the other pods for the Route

Exec in to a pod and then do ` nc -w 3 <route> 6222`

If you can't connect then your k8s networking isn't working right

**Comment by Vaibhavi-Tanla** [comment]
Hello @Caleb ***@***.***>,

I did the below, I'm able to receive response

***@***.***

And despite still getting below errors


[7] 2022/12/28 04:44:18.895977 [INF] 192.168.100.4:61846 - rid:46 - Route connection created
[7] 2022/12/28 04:44:24.904100 [INF] 192.168.100.4:61846 - rid:46 - Router connection closed: Read Error
[7] 2022/12/28 04:44:24.906082 [INF] 192.168.100.4:40938 - rid:49 - Route connection created

Thanks and Regards,

***@***.***
Vaibhavi Suri
Devops-Engineer-II
[https://tanla.com/signature/phone.png]
+91 8374370675
[https://tanla.com/signature/email.png]
***@***.******@***.***>
[https://tanla.com/signature/web.png]
www.tanla.com<https://ind01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.tanla.com%2F&data=05%7C01%7CVaibhavi.Suri%40tanla.com%7Cea9f01cdd21b46fa7cdb08da26b9d12b%7Cab758891bfde44ba8f4d49ed229d9156%7C0%7C0%7C637864876771125807%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WNeYwI61%2Fzs4BsqOSMfBjOR7GpVGPejaoCs71a9WFjU%3D&reserved=0>
Follow us at:
[https://tanla.com/signature/fb.png]<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Ftanlasolutions%2F&data=05%7C01%7CVaibhavi.Suri%40tanla.com%7Cea9f01cdd21b46fa7cdb08da26b9d12b%7Cab758891bfde44ba8f4d49ed229d9156%7C0%7C0%7C637864876771125807%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3xOCBLo2RLqnRzFW2snFUay1kCSRCtDtr5dgLUs%2Btrk%3D&reserved=0>
[https://tanla.com/signature/tw.png]<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FTanla_India&data=05%7C01%7CVaibhavi.Suri%40tanla.com%7Cea9f01cdd21b46fa7cdb08da26b9d12b%7Cab758891bfde44ba8f4d49ed229d9156%7C0%7C0%7C637864876771125807%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DusbzXhfSz%2FvdUz3C1dLIUOXvIIYZUHbGMDfpty4Jww%3D&reserved=0>
[https://tanla.com/signature/in.png]<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ftanla-solutions%2F&data=05%7C01%7CVaibhavi.Suri%40tanla.com%7Cea9f01cdd21b46fa7cdb08da26b9d12b%7Cab758891bfde44ba8f4d49ed229d9156%7C0%7C0%7C637864876771125807%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vZq%2Fh3%2Bnm0wbDpjoI8pLOUMLq5wzZ5PPKrGjPDM0oL0%3D&reserved=0>

[A picture containing text  Description automatically generated]

Disclaimer : This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by Vaibhavi-Tanla** [comment]
PS D:\NATS\Fresh> kubectl exec -it nats-hub-0 -n nats -- sh
Defaulted container "nats" out of: nats, reloader, metrics
/ # nc -w 3 nats-hub-1.nats-hub.nats.svc.cluster.local 6222
INFO {"server_id":"NDI7AMOKGFKMCTITZLR4VL4D4NU3HP3U7UDA5ILJ5U4RTEW64B4DOP6M","server_name":"nats-hub-1","version":"2.9.10","proto":2,"go":"go1.19.4","host":"nats-hub-1.nats-hub.nats.svc.cluster.local","port":6222,"headers":true,"max_payload":1048576,"ip":"nats-route://nats-hub-1.nats-hub.nats.svc.cluster.local:6222/","nonce":"8qQQoPHIs92AVUE","cluster":"tanla-hub-cluster","connect_urls":["10.220.2.139:4222"],"lnoc":true}
PING

**Comment by caleblloyd** [comment]
The error looks environment-specific.  If you can supply a Helm Chart `values.yaml` file that can re-create the issue on other Kubernetes clusters then I can re-open and debug further.
