### ISSUE TITLE
Add resource specification for test-request-reply pod

### ISSUE THREAD

**Issue by ypoplavs** [nats-io/k8s#627]
Hello team,
Could you please add an option to specify resources for a `nats-box` container in `test-request-reply` pod. Other resources have it, only this one is missing. 

Thank you in advance.

**Comment by caleblloyd** [comment]
Supported in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats)
