### ISSUE TITLE
Consider adding `auth.timeout` for resolver `type=memory` to the configmap template

### ISSUE THREAD

**Issue by manifest** [nats-io/k8s#633]
We are using Core NATS in our web application (via Web Sockets) and getting a significant number of “Authentication Timeout” errors. We use JWT tokens with resolver `type=memory`. We issue a new token for each (re-)connection. The server is not loaded. There is no cpu throttling since we don’t set any cpu limit.

We'd like to experiment with increasing the authorization timeout, but the configuration parameter `auth.timeout` doesn't have an effect for `type=memory`.

**Comment by manifest** [comment]
![Screenshot 2023-01-10 at 12 06 03](https://user-images.githubusercontent.com/439058/211514090-114dde3a-81df-45a0-980c-7f336e2ec03a.jpg)

**Comment by caleblloyd** [comment]
Supported in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats)
