### ISSUE TITLE
Helm: Official repo 404 trying to fetch READMEs

### ISSUE THREAD

**Issue by palsivertsen** [nats-io/k8s#64]
All official Nats repositories are 404'ing:
https://hub.helm.sh/charts/nats/nats
https://hub.helm.sh/charts/nats/nats-account-server
https://hub.helm.sh/charts/nats/stan

Looks like 469fc58193d3b9d4c86e45f53e623fa381cf61b0 did not update `helm/charts/index.yaml`

**Comment by jdolce** [comment]
It's not clear what that site is doing. I think they are asking for a README.md file that doesn't exist. But the index.yaml file is being served correctly, so you should still be able to download the charts.
https://nats-io.github.io/k8s/helm/charts/index.yaml

**Comment by wallyqs** [comment]
This looks like a bug in Helm and they are still looking at it... In the meantime this can be used as well: https://artifacthub.io/packages/helm/nats/nats

**Comment by wallyqs** [comment]
Will close this one since it is an upstream issue with the Helm site 🤷‍♂️
