### ISSUE TITLE
[nats] Enable enableHealthzLivenessReadiness check as default 

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#657]

**Comment by caleblloyd** [comment]
It is the default in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats) - should we worry about enabling it by default in 0.x still?

**Comment by wallyqs** [comment]
still some rough edges but it is close, maybe by v2.10

**Comment by caleblloyd** [comment]
enabled by default in 1.0.0
