### ISSUE TITLE
NATS chart: unable to update labels

### ISSUE THREAD

**Issue by avisser** [nats-io/k8s#662]
From an empty cluster:
```shell
helm install nats nats/nats --set 'nats.selectorLabels.role=nats-server'
```
then, you decided you'd like an additional label on your Service or Pods so you upgrade
```shell
helm upgrade nats nats/nats --set 'nats.selectorLabels.role=nats-server' --set 'nats.selectorLabels.priority=critical-service' --atomic
```
results in `Error: UPGRADE FAILED: release nats failed, and has been rolled back due to atomic being set: cannot patch "nats" with kind StatefulSet: StatefulSet.apps "nats" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden`

This is due to the fact that [`nats.labels` includes `nats.selectorLabels`](https://github.com/nats-io/k8s/blob/5c319a5aa0ad54c50af17614535ca4783308308a/helm/charts/nats/templates/_helpers.tpl#L36-L41) (where `nats.selectorLabels` includes the user provided `.Values.nats.selectorLabels`)

and the fact that [`nats.labels` is used to populate the `metadata.labels` of the StatefulSet](https://github.com/nats-io/k8s/blob/5c319a5aa0ad54c50af17614535ca4783308308a/helm/charts/nats/templates/_helpers.tpl#L36-L41)

Not sure the right way to address this - maybe new values `.Values.nats.serviceLabels` or `.Values.nats.podLabels` that are targeted and avoid updating `metadata.labels` of the StatefulSet.

My current workaround is to manually update the statefulSet podTemplate to include the new values.

**Comment by caleblloyd** [comment]
This is unfortunately how Stateful Sets work and there is nothing we can really do about it.  [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats) has capabilities to patch any resource, so Selector Labels can be removed by patching starting in that version
