### ISSUE TITLE
Cannot use custom storageClassName from helm chart nats-0.19.9

### ISSUE THREAD

**Issue by niamR** [nats-io/k8s#667]
Helm chart nats-0.19.9
While using below values, volumes still gets provisioned with the standard storage class.

    cluster:
      enabled: true
      replicas: 3
    
    nats:
      jetstream:
        enabled: true
    
      resources:
        limits:
          cpu: 2
          memory: 4Gi
    
        memStorage:
          enabled: true
          size: 2Gi
    
        fileStorage:
          enabled: true
          size: 10Gi
          storageDirectory: /data/
          storageClassName: "nfs-client"
          accessModes:
            - ReadWriteOnce
    exporter:
      serviceMonitor:
        enabled: true
        labels: {
          release: prometheus
        }
 
    $k get pvc
    NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
    nats-js-pvc-nats-0   Bound    pvc-2cecffda-90d8-4e01-9017-c3eba7ccd4ca   10Gi       RWO            standard       33m
    nats-js-pvc-nats-1   Bound    pvc-8d29dc4c-2320-4571-8258-61ba6606d2aa   10Gi       RWO            standard       33m
    nats-js-pvc-nats-2   Bound    pvc-efe38ca8-1405-499d-a0bb-1224e0ebe4b1   10Gi       RWO            standard       33m
    
    $k get storageclasses.storage.k8s.io
    NAME                 PROVISIONER                                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
    nfs-client           cluster.local/nfs-subdir-external-provisioner   Delete          Immediate           true                   21h
    standard (default)   k8s.io/minikube-hostpath                        Delete          Immediate           false                  3d22h

**Comment by caleblloyd** [comment]
Do not store JetStream data on NFS!  It preforms best on fast, local, block-based storage.

**Comment by caleblloyd** [comment]
also check your YAML - you have `fileStorage` and `memStorage` under `resources` and it should be under `jetstream`

`nats.jetstream.fileStorage.storageClassName`

**Comment by niamR** [comment]
Thanks, work like a charm with proper indent...
Shouldn't it (is that possible to?) output a warning at chart deploy if the values are not compliant thought?

I know for ngs, just a matter of testing purpose here, nfs makes setup easier for my local minikube context.
