### ISSUE TITLE
NATS error installation

### ISSUE THREAD

**Issue by ypoplavs** [nats-io/k8s#668]
Hello team,
While deploying NATS as a helm chart on physical server the pods cannot start dues to the following error:

`unable to start container process: exec: \"/pause\": stat /pause: no such file or director`

Please advise.

**Comment by ypoplavs** [comment]
Hello team,
While deploying NATS as a helm chart on physical server the pods cannot start dues to the following error:

`unable to start container process: exec: \"/pause\": stat /pause: no such file or director`

Please advise.

**Comment by wallyqs** [comment]
what environment is this? are you using the `scratch` or `alpine` image? The pause container is something related to your k8s installation I believe

**Comment by ypoplavs** [comment]
Thank you for such a quick response.

It's an Openshift cluster deployed on physical servers. I can give you more info on that tomorrow.

We use https://github.com/nats-io/k8s helm chart with default images. Here container image for `nats` is `alpine`.

**Comment by ypoplavs** [comment]
```
Warning  FailedCreatePodSandBox  29s (x36 over 8m39s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: time="2023-02-16T10:53:06Z" level=error msg="runc create failed: unable to start container process: exec: \"/pause\": stat /pause: no such file or directory"
```

**Comment by caleblloyd** [comment]
there is no `pause` pod in this chart.  this sounds environment specific, we can't debug environment issues here.
