### ISSUE TITLE
Add option to set namespace selector

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [nats-io/k8s#708]
We are running multiple nats servers on our cluster and would like to have seperate monitors.

Could you add an option to restrict the namespaceSelector?

https://github.com/nats-io/k8s/blob/e0eda12d6062b9f049a7c34b4c9da9f50cb24f64/helm/charts/nats/templates/serviceMonitor.yaml#L31

**Comment by caleblloyd** [comment]
Merging or patching that will be available in the 1.x Helm Chart (https://github.com/nats-io/k8s/pull/704)

It is switching from a ServiceMonitor to a PodMonitor

**Comment by caleblloyd** [comment]
Supported in [nats-1.0.0-beta.0](https://github.com/nats-io/k8s/tree/nats-1.0.0-beta.0/helm/charts/nats)
