### ISSUE TITLE
Announcement: NATS Helm Chart 1.x Beta

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/k8s#713]
The NATS Helm Chart 1.x Beta has been published, and will live on the [helm-nats-1.x branch](https://github.com/nats-io/k8s/tree/helm-nats-1.x/helm/charts/nats) during beta.

The `values.yaml` format has changed significantly, and upgrading from 0.x -> 1.x is not straightforward.  At this time, we are recommending only new installations using the 1.x Beta chart.

We will be developing an upgrade path from 0.x -> 1.x (captured by #712) prior to launching 1.x GA.

The goal of the 1.x Chart is to set good defaults for running NATS in Kubernetes, but also to be extremely flexible for different use cases via `merge` and `patch` operations supported on the NATS Config and every Kubernetes resource.

Options that are typically templated in traditional Helm charts using `toYaml` such as `annotations`, `resources`, `securityContext`, etc are not explicitly defined in the `values.yaml` file, but can be added to resources using `merge` and `patch`.

Feedback and suggestions are welcome!

**Comment by databasedav** [comment]
can we change the test request reply [pod](https://github.com/nats-io/k8s/blob/helm-nats-1.x/helm/charts/nats/templates/tests/request-reply.yaml#L6) to a `Job`? if the pod comes up before the cluster is ready, the command fails and the failed pod is never cleaned up, which is reported as a failure in a git ops system like [`kapp-controller`](https://github.com/carvel-dev/kapp-controller), e.g. an unclean install, plus [bare pods are not recommended](https://kubernetes.io/docs/concepts/workloads/controllers/job/#bare-pods)

**Comment by caleblloyd** [comment]
> can we change the test request reply [pod](https://github.com/nats-io/k8s/blob/helm-nats-1.x/helm/charts/nats/templates/tests/request-reply.yaml#L6) to a Job

Sure, if the tests work the same a job is fine. The pod only doesn't get cleaned up on failure so that you can see the logs from the failure. It'll get cleaned up by the helm hook next time the tests are run. A job would need to work the same way

**Comment by caleblloyd** [comment]
Helm 3 has a flag to select the namespace where the chart is installed - it is the `-n` flag

**Comment by jobaeurle** [comment]
> Helm 3 has a flag to select the namespace where the chart is installed - it is the `-n` flag

I get this, but this doesn't work as soon as the chart is put in another helm chart as a subchart and I want to use different namespaces, right?

**Comment by caleblloyd** [comment]
> this doesn't work as soon as the chart is put in another helm chart as a subchart and I want to use different namespaces

Correct, that would not work. Presently you would have to supply overrides for each resource in the form of `statefulSet.metadata.namespace=x`.  Maybe we could add a `namespaceOverride` option or something along those lines

**Comment by caleblloyd** [comment]
1.0.0-beta.7 includes an [UPGRADING.md](https://github.com/nats-io/k8s/blob/nats-1.0.0-beta.7/helm/charts/nats/UPGRADING.md) that explains how to upgrade from 0.x to 1.x.

**Comment by caleblloyd** [comment]
@jobaeurle `namespaceOverride` is now available in `1.0.0-rc.0`

**Comment by caleblloyd** [comment]
`1.0.0` has been released!
