### ISSUE TITLE
Nats consumers stop consuming messages when 2 of the 3 replicas are restarted.

### ISSUE THREAD

**Issue by bautistamad** [nats-io/k8s#718]
I have nats-jestream deployed in kubernetes with 3 replicas, each one in a different server, the problem is the following:
It already happened to me twice that two of them go down and one of them is still up, the same ones adapt again but the consumers stop consuming the messages from the queue. When I restart the replica that has not fallen back to work correctly, I do not know if it is an issue but I would like to know if there may be a root cause.

I am using version 0.19.5 of the chart.
Nats-server version: 2.9.11

**Comment by caleblloyd** [comment]
What is the stream configuration?  `nats stream info`

**Comment by bautistamad** [comment]
This is my configuration
![image](https://github.com/nats-io/k8s/assets/75149705/7d54a644-309e-4f0a-b8a5-d45a7321e7c7)
![image](https://github.com/nats-io/k8s/assets/75149705/3ebe6cb1-687c-4942-b522-26dcfd92e0ed)

**Comment by caleblloyd** [comment]
How many replicas on the stream?

**Comment by caleblloyd** [comment]
The Startup Probe should ensure that only 1 NATS Server restarts at a time.

You will see your client disconnect, the Client library should automatically reconnect though.  If you are using a 3-replica stream with a 3-replica durable consumer then this should happen very quickly.
