### ISSUE TITLE
Support to integrate with SPIFFE/SPIRE

### ISSUE THREAD

**Issue by venugopalsakamuri** [nats-io/k8s#722]
Currently, The other workloads in the systems has integration with SPIRE/SPIFFEE server to procure and rotate mTLS certs for inter service communication.

1) Does NATS/Jetstream supports integration with SPIFFE/SPIRE to procure TLS certs for servers?
2) Does NATS K8S Helm chart supports any parameters in values.yaml to integrate with SPIRE server running in the same cluster?
3)Do we need to take any additional steps for TLS verification with other workloads that leverage same SPIRE server?

Thanks

**Comment by caleblloyd** [comment]
If you mount TLS secrets then the reloader container will see when they change and issue a reload signal to the server.

If you put the certs in some other way such as mounting to the FS, you can still add extra configuration to the reloader container to watch the certs.
