### ISSUE TITLE
Change nats-box from Deployment to StatefulSet?

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#725]
Using the nats-box container for stream/account backups and snapshots is getting pretty common in production operations, so thinking that when there is JetStream support we could have an option so that it is straightforward to have it attach a volume (dynamically so via the volume claim templates features from StatefulSets would be convenient).

**Comment by wallyqs** [comment]
That might work, I was thinking of way we could offer this for users with less knobs, so thought that the most straightforward way might be to let the mounting happen automatically via the volume claim template when they have JS enabled maybe.

**Comment by caleblloyd** [comment]
Stateful Sets are hard to upgrade - so many immutable options.  Let's keep it a Deployment.  Adding a volume to it in 1.x is fairly straightforward.
