### ISSUE TITLE
Please add option to add priorityClassName to the helm chart

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [nats-io/k8s#726]
Thank you!

**Comment by caleblloyd** [comment]
In the `1.x-beta` chart you can set anything on the resources created with `merge` and `patch`.

`podTemplate.merge.spec.priorityClassName`

Check out the README on [this branch](https://github.com/nats-io/k8s/tree/helm-nats-1.x/helm/charts/nats) for more details

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah thank you! Any estimate when the beta branch gets released as new major version?

**Comment by caleblloyd** [comment]
As soon as we can build an upgrade path from 0.x. That will probably take a couple months
