### ISSUE TITLE
Add HPA scaler

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [nats-io/k8s#727]
Hi,

would it be possible that you add an option to create an autoscaler (HPA)?

Or at least mention it how to do it in the documentation? Is it just possible to scale over CPU consumption?

Thank you!

**Comment by caleblloyd** [comment]
No, NATS becomes Stateful once you add JetStream so dynamic scaling is not a good idea.

The best thing to do is benchmark your setup and set resources accordingly.

A good starting point for a production setup is 2 cores and 8Gi memory per pod.

**Comment by h0jeZvgoxFepBQ2C** [comment]
But without using JetStream? We are just pushing out realtime data, no need to persist things for us?

**Comment by caleblloyd** [comment]
Core NATS without JetStream can handle millions of messages per second without using many resources. HPA is usually over complicating the architecture

Still you can add one with `extraResources` in the 1.x chart.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I see, the thing is that we are an event company which offers realtime votings f.e. Each customer should get a dedicated nats installation, which needs to offer high availability + scaling - but most of the time our server is not used very much (except on the event day itself, but not before and not much afterwards). Right now we are scaling our general webserver resources with the HPA, which works nicely.. But having NATS running with a static size is not really optimal for us - either we waste a lot of unneeded server resources (which costs a lot of money if you have > 100 customers with each a nasts cluster) - or we have to scale them manually by deploying a fixed size - which is also not really nice, since it's not scaling automatically?

So this is the background why I ask for an HPA integration..
