### ISSUE TITLE
leaf accounts in helm v1.x

### ISSUE THREAD

**Issue by jleni** [nats-io/k8s#737]
This does not seem to work anymore:

https://github.com/nats-io/nats.docs/blob/master/running-a-nats-service/nats-on-kubernetes/helm-charts.md#leafnodes

Adding credentials for leaf remotes seems to be missing in v1

**Comment by caleblloyd** [comment]
To only configure leafnodes remotes, use `config.merge.leafnodes.remotes`

The value will be an array of:

https://docs.nats.io/running-a-nats-service/configuration/leafnodes/leafnode_conf#leafnode-remotes-entry-block
