### ISSUE TITLE
Allow overriding of service name via values.yaml

### ISSUE THREAD

**Issue by IAXES** [nats-io/k8s#74]
Can we modify the name of the service object so that it can be customized via `values.yaml`? i.e. change it from this:

```yaml
 {{- default .Release.Name -}}
```

To something like so:

```yaml
 {{- default .Release.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | trimSuffix "." -}}
```

I have a top-level chart that pulls in nats-operator alongside other charts, and there are cases where a top-level chart has two third-party sub-charts that use `{{- default .Release.Name -}}` for the name of a service object (resulting in a naming collision). It'd be great to be able to override this outright.

**Comment by wallyqs** [comment]
Fixed via #62
