### ISSUE TITLE
Passing max_traced_msg_len via Helm

### ISSUE THREAD

**Issue by atilag** [nats-io/k8s#742]
Hi team!
I need to enable tracing and limit the length of the payload that is shown in the logs, but I couldn't find a way to pass a `max_traced_msg_len`  value using helm variables.
Is there a way I didn't realize yet to make this happen? :)

Thanks!

**Comment by caleblloyd** [comment]
In the Hem 1.x Beta chart it is:

```
config:
  merge:
    max_traced_msg_len: 123
```
