### ISSUE TITLE
nats chart does not propagate automountServiceAccountToken setting to ServiceAccount YAML

### ISSUE THREAD

**Issue by dmglennie-diveplane** [nats-io/k8s#750]
Whilst you can set automountServiceAccountToken, doing so will set the value in the statefulset spec, but not the serviceaccount itself.  Possibly redundant, but it will be clearer if it does there too.  In my case it is getting flagged by some auditing software.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting

**Comment by caleblloyd** [comment]
Check out the 1.x-beta chart, it will be promoted to 1.0.0 soon.  It can do this already.

**Comment by dmglennie-diveplane** [comment]
Great, thanks - I shall wait for that.
