### ISSUE TITLE
Deprecated apiVersions in dependencies

### ISSUE THREAD

**Issue by ccokee** [nats-io/k8s#776]
Please update dependency versions. setup.sh is broken due the old release v0.11.0 for certmanager. Which has old apiVersions for CRDs causing misbehaving during install in new k8s environments.

This also happens with prometheus operator which uses "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"

**Comment by caleblloyd** [comment]
The stale documentation example has been removed.
