### ISSUE TITLE
helm charts v1.0.0 nukes image pull secrets

### ISSUE THREAD

**Issue by treksler** [nats-io/k8s#789]
looks to me like since v1.0.0 image pull secrets are gone from the nats chart, which obviously makes the chart useless if you're using a private registry and authenticating with pull secrets
https://github.com/nats-io/k8s/pull/770

**Comment by treksler** [comment]
```
Ristos-M1-MacBook-Pro:nats rtreksler$ git checkout main
Ristos-M1-MacBook-Pro:nats rtreksler$ ack -ri imagepullsecrets .
Ristos-M1-MacBook-Pro:nats rtreksler$ git checkout nats-0.19.17
Ristos-M1-MacBook-Pro:nats rtreksler$ ack -ri imagepullsecrets .
README.md
888:imagePullSecrets:
896:  imagePullSecrets:

templates/nats-box.yaml
65:      {{- with .Values.imagePullSecrets }}
66:      imagePullSecrets:

templates/statefulset.yaml
52:      {{- with .Values.imagePullSecrets }}
53:      imagePullSecrets:

values.yaml
352:# An array of imagePullSecrets, and they have to be created manually in the same namespace
354:imagePullSecrets: []
557:  # An array of imagePullSecrets, and they have to be created manually in the same namespace
559:  imagePullSecrets: []
```

0.19.17 appears to be last usable version

**Comment by caleblloyd** [comment]
```
podTemplate:
  merge:
    spec:
      imagePullSecrets:
      - name: regcred
```

**Comment by caleblloyd** [comment]
For natsBox it should be

natsBox.deployment.merge.spec.imagePullSecrets

Since this appears in a couple places we could look at adding it to global.image

**Comment by caleblloyd** [comment]
#790

**Comment by treksler** [comment]
ok, that's neat for merging arbitrary stuff. 

I agree that this is a common enough a use case that it should be in global.image. Thanks for the reply

**Comment by mm-dibuco** [comment]
you should use the following for NATS-Box:
natsBox.**podTemplate**.merge.spec.imagePullSecrets

(change deployment with podTemplate)
This works for me.
