### ISSUE TITLE
Re-add nodeSelector to helm chart

### ISSUE THREAD

**Issue by hero-david** [nats-io/k8s#798]
### What motivated this proposal?

I have been looking at upgrading to the latest version of the Helm chart, but it's looking like more effort than it's worth to migrate, plus we seem to miss out on basic options that we'd expect from a chart, like the ability to specify a `nodeSelector`.
I'm not super stoked to have to write json patches to achieve this, it seems like a step backwards. 

### What is the proposed change?

Add a `config.nodeSelector` or honour the previous top level `nodeSelector` label

### Who benefits from this change?

Helm users will benefit by not having to understand the chart internals / containers to apply common configuration items

**Comment by caleblloyd** [comment]
The directive in 1.x is:

`podTemplate.merge.spec.nodeSelector`

> I have been looking at upgrading to the latest version of the Helm chart, but it's looking like more effort than it's worth to migrate

You can stay on 0.x and keep moving the image tag to match the nats server version that you want.

> I'm not super stoked to have to write json patches to achieve this, it seems like a step backwards

It's a balancing act. As chart developers we were getting feature requests to add pretty much every single option to the values file in 0.x.

So in 1.x we decided if we were simply re-mapping a key to another key that we would offer the ability to `merge` instead.
