### ISSUE TITLE
NATS Chart Probes not Using HTTPS when Monitor TLS is Enabled

### ISSUE THREAD

**Issue by rozidan** [nats-io/k8s#805]
Hey!

K8S version: **1.25.3**
Nats chart version: **nats-v1.1.0**

**Defect:**
When `config.monitor.tls` is enabled, probes are generated with the default `httpGet.scheme` "`HTTP`", but it should be "`HTTPS`".

**Fix suggestion:**
In '_files/stateful-set/nats-container.yaml_', add the following to each probe

```
{{- if .Values.config.monitor.tls.enabled }}
scheme: HTTPS
{{- end }}
```

Thanks.

**Comment by caleblloyd** [comment]
Great suggestion!
