### ISSUE TITLE
Helm: provide a means to specify ca.crt for STAN

### ISSUE THREAD

**Issue by kylos101** [nats-io/k8s#82]
Hi,

I recently setup NATS Operator, and secured NATS with TLS following the cert-manager examples. Thank you so much for those! Very slick.

One thing I noticed, is that the Helm chart for STAN lacks a means to make it possible for users to share the ca.crt with STAN. As a result, on start-up I get this:

```
kubectl logs stan-0 stan
[1] 2020/07/13 13:28:37.149271 [INF] STREAM: Starting nats-streaming-server[stan] version 0.17.0
[1] 2020/07/13 13:28:37.149378 [INF] STREAM: ServerID: 59VFuL42d7arsWQkUJUCa7
[1] 2020/07/13 13:28:37.149382 [INF] STREAM: Go version: go1.13.7
[1] 2020/07/13 13:28:37.149384 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/07/13 13:28:37.166684 [INF] STREAM: Shutting down.
[1] 2020/07/13 13:28:37.166760 [FTL] STREAM: Failed to start: x509: certificate signed by unknown authority
```

I am guessing that I am getting that, because my `stan-0` pod has no knowledge of the related ca.crt. For the interim, [I'll setup STAN w/o using Helm](https://github.com/nats-io/k8s/blob/master/nats-streaming-server/nats-streaming-auth-and-tls.yml), but thought this would be a nice add for the chart.

Take care,

Kyle

**Comment by kylos101** [comment]
@wallyqs hi there! :) Would it be okay for me to open a PR for this issue? 

I started working on a fix [here](https://github.com/kylos101/k8s/commit/17816f7beeb96fbdf7510da2e7e9fce221cfde91). It work when `store.cluster.enabled` is `true`. For example, when I try connecting with nats-box without having the CA setup, I get this error `x509: certificate signed by unknown authority`. 

I still need to do testing when `store.cluster.enabled` is `false`...so more commits will be coming.

**Comment by kylos101** [comment]
> @wallyqs hi there! :) Would it be okay for me to open a PR for this issue?
> 
> I started working on a fix [here](https://github.com/kylos101/k8s/commit/17816f7beeb96fbdf7510da2e7e9fce221cfde91). It work when `store.cluster.enabled` is `true`. For example, when I try connecting with nats-box without having the CA setup, I get this error `x509: certificate signed by unknown authority`.
> 
> I still need to do testing when `store.cluster.enabled` is `false`...so more commits will be coming.

@wallyqs may I ask for you to peek at this commit, to let me know if you'd like a PR for this too? I just want to make sure I am heading in the right direction.

**Comment by wallyqs** [comment]
@kylos101 took a look at the commits and they look good to me, thanks again!

**Comment by kylos101** [comment]
Closing, this was taken care of in #85
