### ISSUE TITLE
Helm: create a chart for nats-box, with support for TLS

### ISSUE THREAD

**Issue by kylos101** [nats-io/k8s#83]
Hi there,

I'd be happy to create a chart for this, if its something that you think would add value. Please let me know?

Thanks,

Kyle

**Comment by wallyqs** [comment]
Thanks @kylos101 yes that would help a lot, I was thinking maybe something like this maybe? https://github.com/nats-io/k8s/issues/80

**Comment by kylos101** [comment]
I will close this and start working on #80
