### ISSUE TITLE
Support `mappings` in nats config

### ISSUE THREAD

**Issue by yz89122** [nats-io/k8s#834]
### What motivated this proposal?

In NATS, there's a per stream throughput limitation. Currently, I do [partitioning](https://docs.nats.io/nats-concepts/subject_mapping#deterministic-subject-token-partitioning) to achieve higher throughput, which distributes messages to multiple streams.

To configure this in current Helm Chart, I have to [edit the ConfigMap](https://docs.nats.io/running-a-nats-service/configuration/configuring_subject_mapping) after Helm template generation.

### What is the proposed change?

Support [subject mapping](https://docs.nats.io/running-a-nats-service/configuration/configuring_subject_mapping) in values.yaml.

### Who benefits from this change?

Anyone who needs to configure subject mapping.

### What alternatives have you evaluated?

 - JetStream Stream subject transformation, which is different from subject mapping.

**Comment by caleblloyd** [comment]
Any config supported by NATS configuration can be put into `config.merge`
