### ISSUE TITLE
volumeClaimTemplates can't sync with argocd

### ISSUE THREAD

**Issue by MikeDevresse** [nats-io/k8s#847]
### What version were you using?

2.10.7

### What environment was the server running in?

Docker image on kubernetes (eks)

### Is this defect reproducible?

When installing the helm chart in cluster mod with fileStore, sometimes the app is not syncing in argocd because small diff with how the volumeClaimTemplate is defined.

![image](https://github.com/nats-io/k8s/assets/2046091/aab3bffb-3a1d-4e75-b26e-f31d381f3890)

### Given the capability you are leveraging, describe your expectation?

This doesn't change anything except for the fact that the argocd app is always out of sync.

### Given the expectation, what is the defect you are observing?

ArgoCD app is out of sync

**Comment by caleblloyd** [comment]
Are you using `ServerSideApply=true`?  Looks like this is related to https://github.com/argoproj/argo-cd/issues/11143 which is still open

Examples in the [https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates](Kubernetes Docs) do not explicitly set an `apiVersion` or `kind` on `volumeClaimTemplates`, so I don't think we should do it here.  Probably better to workaround it in ArgoCD by ignoring that difference, there are some suggestions in the ArgoCD Issue thread for how to do that

**Comment by MikeDevresse** [comment]
Yes that fixed it, If you think it's better to not set it then we can close the issue and PR
