### ISSUE TITLE
Make pid file and config file defaults for nats helm chart and for the natsio/nats-server-config-reloader image match

### ISSUE THREAD

**Issue by anthonyjacques20** [nats-io/k8s#851]
### What motivated this proposal?

When trying to get the `nats-server-config-reloader` to function, it wasn't working with the defaults and it required me to dig into it and add arguments to the `nats-server-config-reloader`.

The defaults don't match for the `nats` helm chart and the `natsio/nats-server-config-reloader`
| Argument | Default `nats` helm chart | Default `nats-server-config-reloader` |
| --- | --- | --- |
| pid file | `/var/run/nats/nats.pid` | `/var/run/nats/gnatsd.pid` |
| config file | `/etc/nats-config/nats.conf` | `/etc/nats-config/gnatsd.conf` |

### What is the proposed change?

The proposed change is to make the defaults match (by changing either side)

### Who benefits from this change?

Everyone trying to use the `nats-server-config-reloader` should benefit from this as it will work by default instead of requiring extra understanding/configuration.

### What alternatives have you evaluated?

I was able to get the `nats-server-config-reloader` to function by adding arguments for the `pid file` and the `config file` but it's just another step/thing to figure out.

I referenced the `nats-server-config-reloader` code from [github here](https://github.com/plgd-dev/hub/blob/v2.16.1/tools/nats-server-config-reloader/pkg/natsreloader/natsreloader.go) but I'm not sure if that is correct since it doesn't appear to be an official `nats` account.

**Comment by caleblloyd** [comment]
These changes were made in https://github.com/nats-io/nack/commit/e7edc6d772adcd4379dce082c82826096c666115#diff-0ae4008ed553e68e57b9d91a386a41e3e9899b70e516eb46f2deb10e8d32f6c2 and will be in the next nats-server-config-reloader release
