### ISSUE TITLE
server-config-reloader has a non existing tag in the values.yaml of the helm chart

### ISSUE THREAD

**Issue by hugonijmek** [nats-io/k8s#856]
### What version were you using?

2.10.9

### What environment was the server running in?

kubernetes helm chart

### Is this defect reproducible?

yes it is reproducible, install using helm on Kubernetes and this should prevent the pods from starting up.

### Given the capability you are leveraging, describe your expectation?

I expect the values.yaml to contain a tag for the server-config-reloader that is actually available

### Given the expectation, what is the defect you are observing?

The helm chart is currently unable to run using the default values.yaml.

**Comment by hugonijmek** [comment]
to add, I changed the tag in my local values.yaml to 0.14.1 instead of the 0.14.2 and it's running smoothly. It seems this was changed accidentally alongside a nats-box version update #854

**Comment by caleblloyd** [comment]
ugh, Dependabot problems strike again.  thx for reporting
