### ISSUE TITLE
[Helm][STAN] Latest version of STAN does not seem to be available

### ISSUE THREAD

**Issue by emaincourt** [nats-io/k8s#88]
Hi,

The latest (0.5.0) version of STAN's Helm chart does not seem to be available. Trying to pull it gives the following error:

```sh
$ helm repo add nats https://nats-io.github.io/k8s/helm/charts/
"nats" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nats" chart repository
$ helm pull nats/stan
Error: failed to fetch https://github.com/nats-io/k8s/releases/download/v0.5.0/stan-0.5.0.tgz : 404 Not Found
```

I do not exactly know how releases work here but it should be easily fixable.

Thanks for reading

**Comment by wallyqs** [comment]
Thanks for the report, the artifacts were missing in the release tag... It should be fixed now. https://github.com/nats-io/k8s/releases/tag/v0.5.0

**Comment by emaincourt** [comment]
@wallyqs I confirm it's working now. Thanks for your reactivity !
