### ISSUE TITLE
nats-0 CLBackoff, nats-surveyor CLB, stan-1 pending

### ISSUE THREAD

**Issue by jwtodd** [nats-io/k8s#9]
firstly, thx for the one-liner install :]

env: osx, docker-desktop/kubernetes latest, reset

test: % `curl -sSL https://nats-io.github.io/k8s/setup.sh | sh`

pods:
```
jwtodd> kubectl get pods
NAME                                     READY   STATUS                  RESTARTS   AGE
nats-0                                   0/3     Init:CrashLoopBackOff   5          5m38s
nats-box                                 1/1     Running                 0          5m39s
nats-setup                               0/1     Completed               0          6m9s
nats-surveyor-68fc4bbcc8-8bttt           0/1     CrashLoopBackOff        5          5m33s
nats-surveyor-grafana-55fb5584b6-vjf4f   1/1     Running                 0          5m34s
prometheus-nats-prometheus-0             3/3     Running                 1          5m25s
prometheus-nats-surveyor-0               3/3     Running                 1          5m25s
prometheus-operator-6d899fc8dd-47d78     1/1     Running                 0          5m37s
stan-0                                   2/2     Running                 1          5m38s
stan-1                                   0/2     Pending                 0          5m33s
```

logs:
```
jwtodd> kubectl logs nats-0
Error from server (BadRequest): a container name must be specified for pod nats-0, choose one of: [nats reloader metrics] or one of the init containers: [bootconfig]
jwtodd> kubectl logs nats-surveyor-68fc4bbcc8-8bttt
+ cp /etc/nats/certs/ca.crt /usr/local/share/ca-certificates
+ ls -al /usr/local/share/ca-certificates
total 12
drwxr-xr-x    1 root     root          4096 Nov 22 23:19 .
drwxr-xr-x    1 root     root          4096 Jul 18 16:53 ..
-rw-r--r--    1 root     root          1115 Nov 22 23:19 ca.crt
+ update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
+ /nats-surveyor '-s=tls://nats:4222' '-c=3' '-creds=/var/run/nats/creds/sys/sys.creds' '-observe=/etc/nats/observations/'
2019/11/22 23:19:26 couldn't start surveyor: nats: no servers available for connection
jwtodd> kubectl logs stan-1
Error from server (BadRequest): a container name must be specified for pod stan-1, choose one of: [stan metrics]
```

ask: is there a means to cleanup the install? to get it teardown i opted for a dd/k8s reset

**Comment by wallyqs** [comment]
Thanks for the bug report, I’ll take a look at making it work in docker desktop. Also there is a destroy.sh script in the repo that can cleanup the install.

**Comment by shyam-unnithan** [comment]
Thanks for the installer :). I am also facing similar issue. Running the installer on minikube. Here are the logs. Hope it helps
kubectl logs nats-0 bootconfig                                               
time="2019-12-19T09:15:21Z" level=info msg="Starting NATS Server boot config v0.5.2"
time="2019-12-19T09:15:21Z" level=info msg="Pod running on node \"minikube\""
**time="2019-12-19T09:15:21Z" level=fatal msg="Could not find external IP address."**

**Comment by mariogruizdiaz** [comment]
I am having the issue;

![image](https://user-images.githubusercontent.com/24963928/84532346-7b426780-acbc-11ea-94c5-cba4e80868b9.png)

kubectldescribe pod nats0
![image](https://user-images.githubusercontent.com/24963928/84532477-afb62380-acbc-11ea-8777-477f1877f9b3.png)


Any idea?

**Comment by ruyang-cloudnatix** [comment]
I'm facing the same issue in the setup.sh script. Any updates on a fix?

**Comment by greg-md** [comment]
Same.

**Comment by MaxThom** [comment]
same

**Comment by eonward37** [comment]
![image](https://user-images.githubusercontent.com/62815458/125198815-7a6a6500-e231-11eb-95c0-1f6414483dd9.png)

😓
Does anyone know how to set up an external IP on docker-desktop? 
I can't run minikube on this machine. Just trying to get around this temporarily.

Thanks for the fix @ZleFox!

**Comment by eonward37** [comment]
![image](https://user-images.githubusercontent.com/62815458/125198963-28760f00-e232-11eb-859c-4b580a57fe7d.png)

😓
Does anyone know how to set up an external IP on docker desktop?
I can't run minikube on this machine. Just trying to get around this issue temporarily

Thank you @ZleFox for the fix!

**Comment by plaisted** [comment]
Scraping through the operator source led me to this solution if your setup is failing due to no external IP address set on the node:

```kubectl label node my-node-wsl nats.io/node-external-ip=192.168.100.100```

**Comment by caleblloyd** [comment]
I don't think this is an issue anymore in recent versions
