### ISSUE TITLE
Microk8s can't bring up nats/stan from minimal setup

### ISSUE THREAD

**Issue by mar1ged** [nats-io/k8s#90]
I followed the docs at https://github.com/nats-io/nats.docs/blob/master/nats-on-kubernetes/minimal-setup.md and ran the nats-box. But stan is not available.

I already checked the status of the pod:
```
NAME     READY   STATUS    RESTARTS   AGE
nats-0   1/1     Running   0          89s
stan-0   0/1     Pending   0          5m12s
```

To exclude this as a cause I downloaded the provided yaml files and updated them to use the 2.1.7-alpine image of nats and the 0.17.0-linux image. But unfortunately I still see the same effect.

**Comment by caleblloyd** [comment]
Closing due to age of issue; if experiencing in current versions please open a new issue.
