### ISSUE TITLE
stan ft-mode requires shared filestore, but k8s-demo yaml creates pvc for each replica

### ISSUE THREAD

**Issue by umialpha** [nats-io/k8s#92]
Hi, to my understanding, in ft mode, each replica will try to acquire the exclusive lock of the shared filestore. If k8s creates one pvc for each replica, how will this be achieved? What's more, if each replica uses independent pvc, the data is not shared.

**Comment by umialpha** [comment]
Yep, I think that makes sense to me. We could close this issue as the PR is already merged.

**Comment by wallyqs** [comment]
Also fixed in the helm charts here #93
