### ISSUE TITLE
 I cant't find the nats-accounts configmap in the nats-server-with-auth-and-tls.yml

### ISSUE THREAD

**Issue by carloscao0928** [nats-io/k8s#98]
just nats-config  , but

![微信截图_20200817112004](https://user-images.githubusercontent.com/58930323/90354343-9f834180-e07b-11ea-8df5-766fb4730fe6.png)

so i can't run

**Comment by caleblloyd** [comment]
Closing due to age of issue; if experiencing in current versions please open a new issue.
